apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: sample-app
  labels:
    app: hello-nginx
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
    - name: http
      port: 80        # Service が受けるポート（ClusterIP側）
      targetPort: 80  # Pod のポート
      nodePort: 30080 # 各ノードで開けるポート（未使用なら固定しなくてもOK）
