apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80          # Service(ClusterIP側)のポート
      targetPort: 8080  # argocd-server コンテナのポート
      nodePort: 32080   # ← 空いてる番号
